-- Step 5 review fixes.

-- 1. Renumber existing messages in time order. 0034 numbered them in
-- physical order, and 0033 had just rewritten every assistant row (moving
-- them to the end of the table), so older transcripts sorted every user
-- message before every bot message. Before this release every message was
-- written in its own short transaction, so created_at order is their true
-- order; id breaks exact ties. New rows keep getting seq at insert, under
-- the conversation row lock, which is the canonical order from here on.
ALTER TABLE "conversation_messages" ALTER COLUMN "seq" SET GENERATED BY DEFAULT;
--> statement-breakpoint
UPDATE "conversation_messages" m
  SET "seq" = r.rn
  FROM (SELECT "id", row_number() OVER (ORDER BY "created_at", "id") AS rn FROM "conversation_messages") r
  WHERE m."id" = r."id";
--> statement-breakpoint
ALTER TABLE "conversation_messages" ALTER COLUMN "seq" SET GENERATED ALWAYS;
--> statement-breakpoint
SELECT setval(
  pg_get_serial_sequence('"conversation_messages"', 'seq'),
  GREATEST((SELECT max("seq") FROM "conversation_messages"), 1)
);
--> statement-breakpoint

-- 2. Timestamps record when the row was actually written (now() is the
-- transaction start). For display and audit only: ordering is by seq.
ALTER TABLE "conversation_messages" ALTER COLUMN "created_at" SET DEFAULT clock_timestamp();
--> statement-breakpoint
ALTER TABLE "inbound_messages" ALTER COLUMN "received_at" SET DEFAULT clock_timestamp();
--> statement-breakpoint

-- 3. When the chat platform says the person sent the message (its own
-- clock). Kept as evidence, not used for ordering: bot messages have no
-- platform time until sent, and platform clocks are not ours.
ALTER TABLE "inbound_messages" ADD COLUMN IF NOT EXISTS "sent_at" timestamptz;
--> statement-breakpoint
ALTER TABLE "conversation_messages" ADD COLUMN IF NOT EXISTS "sent_at" timestamptz;
--> statement-breakpoint

-- 4. Who owns a reflection's answers. Set when the person completes or
-- edits it themselves; analysis then only fills fields they left empty.
-- Existing completed reflections are treated as the person's, so a late
-- re-analysis can never overwrite words someone may have typed.
ALTER TABLE "self_reflections" ADD COLUMN IF NOT EXISTS "person_edited_at" timestamptz;
--> statement-breakpoint
UPDATE "self_reflections" SET "person_edited_at" = COALESCE("completed_at", "updated_at")
  WHERE "status" = 'completed' AND "person_edited_at" IS NULL;
--> statement-breakpoint

-- 5. Web-app conversations (demo, reflections) get their own platform, so
-- the dev simulator's "internal" routing can never reach them.
UPDATE "conversations" SET "platform" = 'web'
  WHERE "platform" = 'internal'
    AND ("platform_channel_id" LIKE 'web:%' OR "platform_channel_id" LIKE 'demo%' OR "platform_channel_id" = 'self-reflection');
